services:

  configserver:
    image: cristianporrety/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - backend
  posts:
    build: ./posts
    ports:
      - 8090:8080
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  profiles:
    build: ./profiles
    ports:
      - 8080:8080
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  backend:
