services:

  grafana:
      image: "grafana/grafana:latest"
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=password
      networks:
       - backend
      depends_on:
        - prometheus  
  
  prometheus:
     image: prom/prometheus:latest
     ports:
        - "9090:9090"
     volumes:
      - ../../posts/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml
     networks:
      - backend
  configserver:
    image: cristianporrety/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - backend
  posts:
    build: ./posts
    ports:
      - 8090:8080
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  profiles:
    build: ./profiles
    ports:
      - 8080:8080
    networks:
     - backend
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  backend:
